### ISSUE TITLE
figure out github actions to sync milestones and labels from main repo to plugins and extensions repos

### ISSUE THREAD

**Issue by sophiathekitty** [sophiathekitty/NullHub#46]
should probably see about making a couple test repos to see if i can get this working.

### main repo 

- [ ] detect when changes have been made to milestones or labels
- [ ] trigger actions on all the repos that need to sync the changes

### secondary repos

- [ ] action that will access the github api to get the milestones and labels
- [ ] make sure all the local labels and milestones match the ones from the main repo
